// Lista embutida de aeroportos, servida junto com a pagina.
//
// Nada de API externa: a busca precisa responder enquanto a pessoa digita, e
// uma chamada de rede por tecla seria lenta e frageis. Sao poucos kilobytes.
//
// Formato: [codigo, cidade, nome do aeroporto, pais ou UF]
// A busca casa por cidade, nome, codigo e sem acento, entao "sao paulo"
// encontra Guarulhos, Congonhas e Viracopos de uma vez.

export const AEROPORTOS = [
  // --- Brasil, sudeste
  ["GRU", "São Paulo", "Guarulhos", "SP"],
  ["CGH", "São Paulo", "Congonhas", "SP"],
  ["VCP", "Campinas", "Viracopos", "SP"],
  ["GIG", "Rio de Janeiro", "Galeão", "RJ"],
  ["SDU", "Rio de Janeiro", "Santos Dumont", "RJ"],
  ["CNF", "Belo Horizonte", "Confins", "MG"],
  ["PLU", "Belo Horizonte", "Pampulha", "MG"],
  ["VIX", "Vitória", "Eurico de Aguiar Salles", "ES"],
  ["SJP", "São José do Rio Preto", "Prof. Eribelto Manoel Reino", "SP"],
  ["RAO", "Ribeirão Preto", "Leite Lopes", "SP"],
  ["BAU", "Bauru", "Arealva", "SP"],
  ["PPB", "Presidente Prudente", "Presidente Prudente", "SP"],
  ["ARU", "Araçatuba", "Dario Guarita", "SP"],
  ["UDI", "Uberlândia", "Ten. Cel. Av. César Bombonato", "MG"],
  ["UBA", "Uberaba", "Mário de Almeida Franco", "MG"],
  ["MOC", "Montes Claros", "Mário Ribeiro", "MG"],
  ["IPN", "Ipatinga", "Vale do Aço", "MG"],
  ["GVR", "Governador Valadares", "Coronel Altino Machado", "MG"],
  ["JDF", "Juiz de Fora", "Francisco de Assis", "MG"],
  ["VAG", "Varginha", "Major Brigadeiro Trompowsky", "MG"],
  ["MII", "Marília", "Frank Miloye Milenkowichi", "SP"],

  // --- Brasil, sul
  ["CWB", "Curitiba", "Afonso Pena", "PR"],
  ["POA", "Porto Alegre", "Salgado Filho", "RS"],
  ["FLN", "Florianópolis", "Hercílio Luz", "SC"],
  ["NVT", "Navegantes", "Ministro Victor Konder", "SC"],
  ["JOI", "Joinville", "Lauro Carneiro de Loyola", "SC"],
  ["XAP", "Chapecó", "Serafin Enoss Bertaso", "SC"],
  ["CCM", "Criciúma", "Diomício Freitas", "SC"],
  ["IGU", "Foz do Iguaçu", "Cataratas", "PR"],
  ["LDB", "Londrina", "Governador José Richa", "PR"],
  ["MGF", "Maringá", "Sílvio Name Júnior", "PR"],
  ["CXJ", "Caxias do Sul", "Hugo Cantergiani", "RS"],
  ["PET", "Pelotas", "João Simões Lopes Neto", "RS"],
  ["RIA", "Santa Maria", "Santa Maria", "RS"],
  ["CSU", "Santa Cruz do Sul", "Santa Cruz do Sul", "RS"],

  // --- Brasil, centro-oeste
  ["BSB", "Brasília", "Presidente Juscelino Kubitschek", "DF"],
  ["GYN", "Goiânia", "Santa Genoveva", "GO"],
  ["CGB", "Cuiabá", "Marechal Rondon", "MT"],
  ["CGR", "Campo Grande", "Campo Grande", "MS"],
  ["BPG", "Barra do Garças", "Barra do Garças", "MT"],
  ["ROO", "Rondonópolis", "Maestro Marinho Franco", "MT"],
  ["SNZ", "Sinop", "Presidente João Figueiredo", "MT"],
  ["DOU", "Dourados", "Dourados", "MS"],
  ["CAC", "Cascavel", "Adalberto Mendes da Silva", "PR"],

  // --- Brasil, nordeste
  ["SSA", "Salvador", "Deputado Luís Eduardo Magalhães", "BA"],
  ["REC", "Recife", "Guararapes", "PE"],
  ["FOR", "Fortaleza", "Pinto Martins", "CE"],
  ["NAT", "Natal", "Aluízio Alves", "RN"],
  ["JPA", "João Pessoa", "Castro Pinto", "PB"],
  ["MCZ", "Maceió", "Zumbi dos Palmares", "AL"],
  ["AJU", "Aracaju", "Santa Maria", "SE"],
  ["THE", "Teresina", "Senador Petrônio Portella", "PI"],
  ["SLZ", "São Luís", "Marechal Cunha Machado", "MA"],
  ["IOS", "Ilhéus", "Jorge Amado", "BA"],
  ["BPS", "Porto Seguro", "Porto Seguro", "BA"],
  ["UNA", "Una", "Comandatuba", "BA"],
  ["LEC", "Lençóis", "Chapada Diamantina", "BA"],
  ["VDC", "Vitória da Conquista", "Glauber Rocha", "BA"],
  ["JJD", "Jijoca de Jericoacoara", "Jericoacoara", "CE"],
  ["FEN", "Fernando de Noronha", "Fernando de Noronha", "PE"],
  ["PNZ", "Petrolina", "Senador Nilo Coelho", "PE"],
  ["JDO", "Juazeiro do Norte", "Orlando Bezerra de Menezes", "CE"],
  ["IMP", "Imperatriz", "Prefeito Renato Moreira", "MA"],
  ["PHB", "Parnaíba", "Prefeito Doutor João Silva Filho", "PI"],
  ["MVF", "Mossoró", "Dix-Sept Rosado", "RN"],
  ["BRA", "Barreiras", "Barreiras", "BA"],

  // --- Brasil, norte
  ["BEL", "Belém", "Val de Cans", "PA"],
  ["MAO", "Manaus", "Eduardo Gomes", "AM"],
  ["PVH", "Porto Velho", "Governador Jorge Teixeira", "RO"],
  ["RBR", "Rio Branco", "Plácido de Castro", "AC"],
  ["BVB", "Boa Vista", "Atlas Brasil Cantanhede", "RR"],
  ["MCP", "Macapá", "Alberto Alcolumbre", "AP"],
  ["PMW", "Palmas", "Brigadeiro Lysias Rodrigues", "TO"],
  ["STM", "Santarém", "Maestro Wilson Fonseca", "PA"],
  ["MAB", "Marabá", "João Correa da Rocha", "PA"],
  ["ATM", "Altamira", "Altamira", "PA"],
  ["TFF", "Tefé", "Tefé", "AM"],

  // --- Europa
  ["LIS", "Lisboa", "Humberto Delgado", "Portugal"],
  ["OPO", "Porto", "Francisco Sá Carneiro", "Portugal"],
  ["FNC", "Funchal", "Cristiano Ronaldo", "Portugal"],
  ["PDL", "Ponta Delgada", "João Paulo II", "Portugal"],
  ["MAD", "Madri", "Barajas", "Espanha"],
  ["BCN", "Barcelona", "El Prat", "Espanha"],
  ["CDG", "Paris", "Charles de Gaulle", "França"],
  ["ORY", "Paris", "Orly", "França"],
  ["LHR", "Londres", "Heathrow", "Reino Unido"],
  ["LGW", "Londres", "Gatwick", "Reino Unido"],
  ["FCO", "Roma", "Fiumicino", "Itália"],
  ["MXP", "Milão", "Malpensa", "Itália"],
  ["AMS", "Amsterdã", "Schiphol", "Holanda"],
  ["FRA", "Frankfurt", "Frankfurt", "Alemanha"],
  ["MUC", "Munique", "Franz Josef Strauss", "Alemanha"],
  ["ZRH", "Zurique", "Kloten", "Suíça"],
  ["BRU", "Bruxelas", "Zaventem", "Bélgica"],
  ["DUB", "Dublin", "Dublin", "Irlanda"],
  ["VIE", "Viena", "Schwechat", "Áustria"],
  ["IST", "Istambul", "Istambul", "Turquia"],

  // --- Americas
  ["MIA", "Miami", "Miami", "Estados Unidos"],
  ["MCO", "Orlando", "Orlando", "Estados Unidos"],
  ["JFK", "Nova York", "John F. Kennedy", "Estados Unidos"],
  ["EWR", "Nova York", "Newark", "Estados Unidos"],
  ["LAX", "Los Angeles", "Los Angeles", "Estados Unidos"],
  ["SFO", "São Francisco", "San Francisco", "Estados Unidos"],
  ["ORD", "Chicago", "O'Hare", "Estados Unidos"],
  ["ATL", "Atlanta", "Hartsfield-Jackson", "Estados Unidos"],
  ["IAD", "Washington", "Dulles", "Estados Unidos"],
  ["BOS", "Boston", "Logan", "Estados Unidos"],
  ["DFW", "Dallas", "Fort Worth", "Estados Unidos"],
  ["IAH", "Houston", "George Bush", "Estados Unidos"],
  ["YYZ", "Toronto", "Pearson", "Canadá"],
  ["YUL", "Montreal", "Trudeau", "Canadá"],
  ["MEX", "Cidade do México", "Benito Juárez", "México"],
  ["CUN", "Cancún", "Cancún", "México"],
  ["PTY", "Cidade do Panamá", "Tocumen", "Panamá"],
  ["BOG", "Bogotá", "El Dorado", "Colômbia"],
  ["LIM", "Lima", "Jorge Chávez", "Peru"],
  ["SCL", "Santiago", "Arturo Merino Benítez", "Chile"],
  ["EZE", "Buenos Aires", "Ezeiza", "Argentina"],
  ["AEP", "Buenos Aires", "Aeroparque", "Argentina"],
  ["COR", "Córdoba", "Ingeniero Taravella", "Argentina"],
  ["MVD", "Montevidéu", "Carrasco", "Uruguai"],
  ["PDP", "Punta del Este", "Laguna del Sauce", "Uruguai"],
  ["ASU", "Assunção", "Silvio Pettirossi", "Paraguai"],
  ["VVI", "Santa Cruz de la Sierra", "Viru Viru", "Bolívia"],

  // --- Africa, Oriente Medio, Asia e Oceania
  ["DXB", "Dubai", "Dubai", "Emirados Árabes"],
  ["AUH", "Abu Dhabi", "Zayed", "Emirados Árabes"],
  ["DOH", "Doha", "Hamad", "Catar"],
  ["TLV", "Tel Aviv", "Ben Gurion", "Israel"],
  ["CMN", "Casablanca", "Mohammed V", "Marrocos"],
  ["JNB", "Joanesburgo", "O. R. Tambo", "África do Sul"],
  ["CPT", "Cidade do Cabo", "Cape Town", "África do Sul"],
  ["ADD", "Adis Abeba", "Bole", "Etiópia"],
  ["LAD", "Luanda", "Quatro de Fevereiro", "Angola"],
  ["MPM", "Maputo", "Maputo", "Moçambique"],
  ["NRT", "Tóquio", "Narita", "Japão"],
  ["HND", "Tóquio", "Haneda", "Japão"],
  ["ICN", "Seul", "Incheon", "Coreia do Sul"],
  ["PVG", "Xangai", "Pudong", "China"],
  ["PEK", "Pequim", "Capital", "China"],
  ["HKG", "Hong Kong", "Hong Kong", "China"],
  ["SIN", "Singapura", "Changi", "Singapura"],
  ["BKK", "Bangkok", "Suvarnabhumi", "Tailândia"],
  ["SYD", "Sydney", "Kingsford Smith", "Austrália"],
  ["AKL", "Auckland", "Auckland", "Nova Zelândia"],
];

/** Versao compacta para o navegador: um array por aeroporto, sem chaves. */
export const AEROPORTOS_JSON = JSON.stringify(AEROPORTOS);

export const CODIGOS = new Set(AEROPORTOS.map((a) => a[0]));
